import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import Vue from 'vue'


import { faFacebookF } from '@fortawesome/free-brands-svg-icons'
import { faTwitter } from '@fortawesome/free-brands-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons'
import { faYoutube } from '@fortawesome/free-brands-svg-icons'
import { faDribbble } from '@fortawesome/free-brands-svg-icons'
import { faUserLock } from '@fortawesome/free-solid-svg-icons'
import { faArrowRightArrowLeft } from '@fortawesome/free-solid-svg-icons'
import { faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons'
import { faPhone } from '@fortawesome/free-solid-svg-icons'
import { faBasketShopping } from '@fortawesome/free-solid-svg-icons'
import { faShop } from '@fortawesome/free-solid-svg-icons'
import { faComments } from '@fortawesome/free-solid-svg-icons'
import { faArrowRight } from '@fortawesome/free-solid-svg-icons'
import { faCartShopping } from '@fortawesome/free-solid-svg-icons'
import { faLocationDot } from '@fortawesome/free-solid-svg-icons'
import { faLeaf } from '@fortawesome/free-solid-svg-icons'
import { faCaretRight } from '@fortawesome/free-solid-svg-icons'
import { faSquarePhoneFlip } from '@fortawesome/free-solid-svg-icons'

import {faEnvelope, faClock} from '@fortawesome/free-regular-svg-icons'
import {faPlus, faMinus} from '@fortawesome/free-solid-svg-icons'
import {faRoad, faVideo, faDroplet, faGear, faBuilding, faChartColumn, faAngleRight, faLink} from '@fortawesome/free-solid-svg-icons'
import { faGoogle, faLinkedinIn} from '@fortawesome/free-brands-svg-icons'
import { faWifi } from '@fortawesome/free-solid-svg-icons'
import { faAngleDown } from '@fortawesome/free-solid-svg-icons'
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons'
import { faFlag } from '@fortawesome/free-solid-svg-icons'
import { faUser } from '@fortawesome/free-solid-svg-icons'
import { faSliders } from '@fortawesome/free-solid-svg-icons'
import { faArrowsSpin } from '@fortawesome/free-solid-svg-icons'
import { faLayerGroup } from '@fortawesome/free-solid-svg-icons'
import { faUserTie } from '@fortawesome/free-solid-svg-icons'
import { faGears } from '@fortawesome/free-solid-svg-icons'
import { faBriefcase } from '@fortawesome/free-solid-svg-icons'
import { faAnglesRight } from '@fortawesome/free-solid-svg-icons'
import { faPlay } from '@fortawesome/free-solid-svg-icons'
import { faCircleCheck } from '@fortawesome/free-solid-svg-icons'
import { faHandHoldingHand } from '@fortawesome/free-solid-svg-icons'
import { faCircleQuestion } from '@fortawesome/free-solid-svg-icons'
import { faBuildingLock } from '@fortawesome/free-solid-svg-icons'
import { faComputer } from '@fortawesome/free-solid-svg-icons'
import { faMagnifyingGlassChart } from '@fortawesome/free-solid-svg-icons'
import { faFileCircleCheck } from '@fortawesome/free-solid-svg-icons'
import { faAward } from '@fortawesome/free-solid-svg-icons'
import { faCubes } from '@fortawesome/free-solid-svg-icons'
import { faFolderOpen } from '@fortawesome/free-solid-svg-icons'
import { faShuttleSpace } from '@fortawesome/free-solid-svg-icons'
import { faPersonDotsFromLine } from '@fortawesome/free-solid-svg-icons'
import { faLaptopCode } from '@fortawesome/free-solid-svg-icons'
import { faPhoneVolume } from '@fortawesome/free-solid-svg-icons'
import { faMessage } from '@fortawesome/free-regular-svg-icons'
import { faCirclePlus } from '@fortawesome/free-solid-svg-icons'
import { faCircleMinus } from '@fortawesome/free-solid-svg-icons'
import { faCloud } from '@fortawesome/free-solid-svg-icons'
import { faChartArea } from '@fortawesome/free-solid-svg-icons'
import { faCodeBranch } from '@fortawesome/free-solid-svg-icons'
import { faFolderTree } from '@fortawesome/free-solid-svg-icons'
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons'
import { faTag } from '@fortawesome/free-solid-svg-icons'
import { faEye } from '@fortawesome/free-solid-svg-icons'
import { faQuoteLeft } from '@fortawesome/free-solid-svg-icons'
import { faUpRightAndDownLeftFromCenter } from '@fortawesome/free-solid-svg-icons'

library.add(faUserLock, faArrowRightArrowLeft, faDribbble, faBasketShopping, faShop, faCartShopping, faSquarePhoneFlip, faEnvelope, faPhone, faPlus, faMinus, faRoad, faVideo, faDroplet, faGoogle, faGear, faBuilding, faChartColumn, faLink, faFacebookF, faTwitter, faLinkedinIn, faWifi, faYoutube, faMagnifyingGlass, faAngleDown, faAngleLeft, faFlag, faClock, faSliders, faAngleRight, faLeaf, faUser, faArrowsSpin, faLayerGroup, faUserTie, faGears, faComments, faBriefcase, faCaretRight, faAnglesRight, faPlay, faCircleCheck, faHandHoldingHand, faCircleQuestion, faBuildingLock, faComputer, faMagnifyingGlassChart, faFileCircleCheck, faAward, faCubes, faFolderOpen, faShuttleSpace, faPersonDotsFromLine, faLaptopCode, faPhoneVolume, faLocationDot, faMessage, faCirclePlus, faCircleMinus, faInstagram, faCloud, faChartArea, faCodeBranch, faFolderTree, faArrowLeft, faArrowRight, faUpRightAndDownLeftFromCenter, faTag, faEye, faQuoteLeft)

Vue.component('font-awesome-icon', FontAwesomeIcon)